---
name: Trunkbased - Main Branch
# on:
#   workflow_call:
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  security-events: write
  actions: write
  pull-requests: write
  packages: write

jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4
        id: release
        with:
          token: ${{ github.token }}
          release-type: node
          default-branch: main
          
      - name: Enable Pull Request Automerge
        if: steps.release.outputs.prs_created == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ github.token }}
          pull-request-number: ${{ steps.release.outputs.pull-request-number }}
          merge-method: squash
